name: testing Actions

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Action 1
        run: echo "Hello from action 1"



  job2:
    runs-on: ubuntu-latest
    steps:
        - name: Action 2 
          run: echo "Hello from action 2"
 

  job3:
    runs-on: ubuntu-latest
    steps:
        - name: Action 4
          run : echo "Hello from action 3"